version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python:3.9
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/santimontaner/weather-console-app/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt          
          pip install .
          nose2

workflows:
  my-custom-workflow:
    jobs:
      - test
